### ISSUE TITLE
Button text does not adjust between light and dark mode

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#935] opened 2023-07-28 18:41 UTC
In current light & dark mode - button text adjusts accordingly - however in `next` - the button text appears dark in light mode. 

Is this a bug with `Next` or do we need to adjust `ouiColorPrimary` to fix any issues with the contrast function?

**Comment by BSFishy** [comment] 2023-08-14 19:04
This is caused by this line:

https://github.com/opensearch-project/oui/blob/fe979c3662afc5e4b620f05c838d4b98beb7573e/src/components/button/_button.scss#L99

Essentially, what's happening is that it thinks those colors are dark mode when it's light mode because of the contrast ratio calculation:

https://github.com/opensearch-project/oui/blob/fe979c3662afc5e4b620f05c838d4b98beb7573e/src/global_styling/functions/_colors.scss#L86-L95

(basically it just chooses the color with the higher contrast ratio)

**Comment by KrooshalUX** [comment] 2023-08-14 19:13
That was my guess - the thing that's driving me crazy is in testing from the color selection light text on the button color passes contrast tests on my end. I will try to adjust the primary as soon as possible to see if that fixes it with the compiler.

**Comment by joshuarrrr** [comment] 2023-08-16 20:12
Just to add some context from the current theme. The default `$ouiColorPrimary` is`#006BB4`. 
https://github.com/opensearch-project/oui/blob/1ff64938a4ab355cd6a61ef5c0fcae33ce27ccf8/src/global_styling/variables/_colors.scss#L20

In the current dark mode overrides, that is adjusted to the lighter `#1BA9F5`
https://github.com/opensearch-project/oui/blob/1ff64938a4ab355cd6a61ef5c0fcae33ce27ccf8/src/themes/oui/oui_colors_dark.scss#L19

In the `next` theme, the light mode `$ouiColorPrimary` is `#159D8D`
https://github.com/opensearch-project/oui/blob/1ff64938a4ab355cd6a61ef5c0fcae33ce27ccf8/src/themes/oui-next/global_styling/variables/_colors.scss#L20

And in `next` dark, it's also `#159D8D`
https://github.com/opensearch-project/oui/blob/1ff64938a4ab355cd6a61ef5c0fcae33ce27ccf8/src/themes/oui-next/oui_next_colors_dark.scss#L19

Note that the `chooseLightOrDaskText` effectively defaults to dark text - it only uses light text if it increases contrast ratio, even if both contrast ratios are sufficiently high. 

Given this, it seems like our preference would be:

1. In `next` theme, `$ouiColorPrimary` is the same in both light and dark modes (already implemente)
2. When styling filled primary buttons, always use light text ($ouiColorGhost)

We can accomplish 2. specifically by adding some conditional logic that doesn't bother calling `chooseLightOrDarkText` for primary filled buttons. Note that this wouldn't change behavior for other color filled buttons. If we wanted a more widespread change to filled button text color, we should either refactor `chooseLightOrDarkText` or write a new function that actually encodes the desired design guidance.

@Kroosh does that assessment sound right to you? I don't think we should let the internal implementation of filled buttons dictate what color you pick for primary.

**Comment by KrooshalUX** [comment] 2023-08-16 20:16
" Note that this wouldn't change behavior for other color filled buttons."  -what other color filled buttons are there? 

I also dont want to change the primary color. I did not realize that button color primary was being updated in the Light/Dark for current - that sounds kind of sketchy to keep trying to chase all these transformations. 

With the font weight having increased on buttons as per #817 , the contrast for light text on the primary color is correct. I dont like that its choosing the higher version even if , as you stated, the desired use is sufficiently high enough. 

I reached out to @BSFishy  with some of these approach shifts as well, so if this is good with you guys, its good with me. The dark text on the primary may be registering higher mathmatically, but its not perceptually correct.

**Comment by joshuarrrr** [comment] 2023-08-16 20:21
> I also dont want to change the primary color. I did not realize that button color primary was being updated in the Light/Dark for current - that sounds kind of sketchy to keep trying to chase all these transformations.

No that's not what's happening. The primary color is not transformed. It's just used to determine which text color to use. I just meant we should be able to get the behavior we want regardless of the choice of primary. But also to note that the `next` theme's approach of the same primary in both modes was a little different.

**Comment by joshuarrrr** [comment] 2023-08-16 20:22
We can go ahead with the simplest fix first, and see the outcome on all the filled button styles: https://oui.opensearch.org/1.2/#/navigation/button

**Comment by joshuarrrr** [comment] 2023-08-28 17:58
fixed by #981

**Closed by joshuarrrr** 2023-08-28 17:58 UTC
Labels: next-theme
