### ISSUE TITLE
Remove "Elastic" Keyword References 

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#67] opened 2022-09-12 16:08 UTC
Remove and Replace all the "Elastic" References with "OpenSearch" or "Appropriate Keyword"

**Comment by bandinib-amzn** [comment] 2022-10-05 01:02
@KrooshalUX As doc site hosting is near finish line, we need to remove or replace "Elastic" reference from all documents? Should we replace with "Opensearch"?

These are references: https://github.com/opensearch-project/oui/search?l=Markdown&q=Elastic

**Comment by KrooshalUX** [comment] 2022-10-05 01:07
Thanks for asking @bandinib-amzn - This should be assigned to me. As discussed with @kaddy645 and @AMoo-Miki last week I will be performing text and imagery edits locally and making appropriate PRs. @AMoo-Miki and I have been working on that process.

**Comment by bandinib-amzn** [comment] 2022-10-06 05:41
Thank you for clarification @KrooshalUX. Looking forward to PRs.

**Comment by KrooshalUX** [comment] 2022-10-11 21:50
Note: No changes should be made to [/CHANGELOG.md](https://github.com/opensearch-project/oui/blob/069f87834fa095b177e0cb38899dd445f9954b84/CHANGELOG.md), as it accurately describes changes to EUI 34.6 and all previous versions.

**Comment by KrooshalUX** [comment] 2022-12-29 21:48
Closing because this is duplicate of a more comprehensive issue

**Comment by KrooshalUX** [comment] 2022-12-29 21:49
Closing because this is duplicate of a more comprehensive issue

**Closed by KrooshalUX** 2022-12-29 21:49 UTC
Labels: OUIDocs
