### ISSUE TITLE
[CCI] Remove unused OuiLoadingElastic and OuiLoadingKibana components 

### ISSUE THREAD

**Issue by SergeyMyssak** [opensearch-project/oui#604] opened 2023-03-18 11:56 UTC
**Is your feature request related to a problem? Please describe.**

Regarding https://github.com/opensearch-project/oui/pull/294, OuiLoadingKibana and OuiLoadingElastic were removed from `loading_examples`, but they were not completely removed from the code base. Also, these components are not used in Dashboards. It would be good to remove them and not make our code messy.

**Describe the solution you'd like**

Remove unused OuiLoadingElastic and OuiLoadingKibana components.

**Comment by KrooshalUX** [comment] 2023-03-18 19:30
@SergeyMyssak Thanks for the issue. 

This is a duplicate of https://github.com/opensearch-project/oui/issues/266. To properly manage the component library versioning, we need to deprecate the component over planned release versions, and not outright removing the code in this current version of OUI. @AMoo-Miki , @BSFishy and I will leave additional information on issue #266 about marking the component for deprecation and then it will become an actionable issue.

**Comment by BSFishy** [comment] 2023-03-18 20:24
@KrooshalUX is right. The strategy would be to deprecate the component in the next `1.x` release (i.e. `1.1`) and then remove it completely in `2.0`, as that is a breaking change. What we could do is have subsequent PR's that are only backported to the correct branches, but will put more info in #266

**Closed by BSFishy** 2023-03-18 20:24 UTC
Labels: enhancement, untriaged
