### ISSUE TITLE
(OUI component update) Update behavior of OuiComboBox with single selection

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/oui#137] opened 2022-11-29 21:42 UTC
`OuiComboBox` component with `singleSelection` prop applied appears to be editable as the cursor stays present after selection is made. 
Although the selection isn't editable, a user could press backspace to delete the selection from the box. The element seems to use that behavior regardless of how its `singleSelection` and `isClearable` settings are configured. It doesn't appear that we have a means of removing the cursor in the component.

**Describe the solution you'd like**

Hide the cursor when selection is made.

**Describe alternatives you've considered**

@AWSHurneyt researched the ways to remove the cursor using the current implementation of the component.  

**Additional context**
Originating from this issue: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/257

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/105245012/204654211-614ac4ab-7926-4e69-8d8f-f8acdab5d04a.gif)

**Comment by KrooshalUX** [comment] 2022-12-14 18:05
@xeniatup  can you give some insight into the "why" of why you would like to remove this cursor. 

In the case of a single selection, the cursor remains in the input box and the user can still utilize the search bar to quickly **replace** the value or to **clear** the value using back space (as per your line "...a user could press backspace to delete the selection from the box."). 

Removing the cursor has deep implications in usability and accessibility for those who interact with the interface primarily via keyboard. It would also impact the interaction across all components utilizing the ComboBox primitive. 

isClearable controls if the X appears to quickly clear the selection, not if the element is immutable or not.

**Comment by kgcreative** [comment] 2022-12-14 19:39
I believe the cursor is intended behavior as that's what allows for searching the drop down if you want to change your selection

**Comment by KrooshalUX** [comment] 2022-12-30 01:04
@kgcreative Are you good with us closing this with "not planned"?`

**Comment by kgcreative** [comment] 2022-12-30 03:24
I'm ok closing as "won't fix"

**Closed** 2022-12-30 03:32 UTC
Labels: discuss
