### ISSUE TITLE
Update all markdown docs with new OUI Website

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#70] opened 2022-09-14 20:10 UTC
Replace - [https://elastic.github.io/eui/#](https://elastic.github.io/eui/#/guidelines/getting-started)
with new OUI DOC site

- [ ] oui/wiki/consuming.md
- [ ] oui/DEVELOPER_GUIDE.md
- [ ] oui/README.md
- [ ] oui/src-docs/src/views/guidelines/getting_started.md
- [ ] oui/wiki/component-development.md
- [ ] oui/wiki/creating-components-manually.md
- [ ] oui/wiki/creating-icons.md
- [ ] oui/wiki/documentation-guidelines.md
- [ ] oui/wiki/releasing-versions.md

**Comment by KrooshalUX** [comment] 2022-12-29 21:50
Closing because this is duplicate of a more comprehensive issue

**Closed by KrooshalUX** 2022-12-29 21:50 UTC
Labels: OUIDocs
